# Generated by Django 5.0.3 on 2024-03-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vendor_options'),
        ('mobApi', '0002_pushnotification'),
        ('userauths', '0005_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications_product', to='core.products'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications_user', to='userauths.usertoken'),
        ),
    ]
