# Generated by Django 5.0.3 on 2024-03-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobApi', '0003_alter_pushnotification_product_and_more'),
        ('userauths', '0005_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='user_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications', to='userauths.usertoken'),
        ),
    ]
