# Generated by Django 5.0.3 on 2024-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobApi', '0004_remove_pushnotification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='token_value',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
