# Generated by Django 5.0.3 on 2024-03-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobApi', '0005_pushnotification_token_value_and_more'),
        ('userauths', '0005_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='token_value',
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications_username', to='userauths.usertoken'),
        ),
    ]
