# Generated by Django 5.0.3 on 2024-03-24 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobApi', '0006_remove_pushnotification_token_value_and_more'),
        ('userauths', '0005_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='token_value',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notification_username', to='userauths.usertoken'),
        ),
    ]
