# Generated by Django 5.0.3 on 2024-03-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobApi', '0007_pushnotification_token_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='user_token',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='username',
        ),
    ]
