# Generated by Django 5.0.3 on 2024-03-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobApi', '0008_rename_user_token_pushnotification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='user_status',
        ),
    ]
