# Generated by Django 5.0.3 on 2024-03-13 22:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='back_image',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
