# Generated by Django 5.0.3 on 2024-03-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'Vendor'},
        ),
    ]
